In [12]:
import pandas as pd

# Existing hotels data
existing_hotels_data = {
    "Radisson Blu": [92.68, 96.49, 90.68, 80.41, 86.04, 93.44],
    "Pride Plaza": [84.38, 73.91, 90.48, 66.07, 82.61, 94.53],
    "Novotel": [83.78, 88.88, 87.07, 78.40, 82.76, 85.18],
    "Lemon Tree": [71.57, 85.29, 78.22, 57.89, 73.73, 75.86],
    "ITC Narmada": [75.47, 92.85, 90.00, 76.67, 75.00, 87.40],
    "Taj": [73.33, 78.13, 83.49, 77.91, 80.60, 87.61],
    "Vivanta": [80.00, 87.10, 81.90, 75.00, 82.69, 87.10],
    "Courtyard Marriott": [61.67, 77.42, 75.65, 71.08, 80.26, 75.47],
    "Ramada": [92.11, 85.71, 87.50, 60.71, 86.36, 80.65],
    "Renaissance": [70.45, 80.00, 64.60, 61.39, 76.06, 64.54],
    "Cama": [72.63, 90.32, 76.92, 71.43, 84.69, 73.68],
    "Cambay": [22.22, 23.91, 28.87, 20.15, 35.85, 23.86],
    "Fortune Park": [75.24, 79.41, 80.95, 60.87, 75.81, 83.67],
    "Four Seasons": [75.00, 76.32, 84.13, 53.21, 80.28, 79.25],
    "Hillock": [90.13, 100.00, 86.54, 74.42, 91.67, 93.18],
    "House of MG": [68.53, 90.00, 75.76, 72.34, 83.18, 62.34],
    "Hyatt Regency": [77.42, 84.38, 78.26, 68.48, 79.10, 78.70],
    "Metropole": [68.63, 68.00, 65.85, 52.13, 84.06, 65.48],
}

# Aspect names
aspects = ["Food", "Clean", "Staff", "Room", "Location", "Service"]

# Create DataFrame for existing hotels
existing_hotels_df = pd.DataFrame(existing_hotels_data, index=aspects).transpose()

# New hotels data
new_hotels_data = {
    "Binori": [68.42, 73.08, 62.16, 65.22, 87.10, 57.32],
    "Courtyard SBR": [61.54, 90.91, 61.39, 63.95, 84.13, 67.07],
    "Crown Plaza": [68.49, 90.00, 81.25, 76.04, 78.95, 83.20],
    "DoubleTree by Hilton": [74.36, 89.66, 76.11, 68.75, 86.15, 74.19],
    "Fairfield Marriott": [60.22, 66.67, 54.46, 39.67, 60.00, 51.85],
    "Fortune Select": [75.35, 66.67, 74.11, 60.44, 82.05, 76.24],
    "Holiday Inn": [79.76, 92.31, 84.95, 44.34, 86.67, 84.92],
    "Hyatt": [80.92, 91.30, 87.16, 64.00, 81.36, 92.44],
}

# Create DataFrame for new hotels
new_hotels_df = pd.DataFrame(new_hotels_data, index=aspects).transpose()

# Additional hotel data
additional_hotels_data = {
    "President": [63.53, 74.36, 62.12, 71.76, 81.67, 68.49],
    "Regenta Central": [69.70, 64.10, 61.84, 55.56, 72.22, 71.76],
    "Ummed": [64.84, 75.00, 66.67, 53.85, 79.10, 60.23],
    "WelcomHotel ITC": [85.26, 85.00, 87.60, 80.65, 80.56, 90.00],
    "Wyndham": [68.75, 65.63, 57.47, 58.49, 70.31, 54.67],
    "Fortune Landmark": [87.50, 80.49, 84.55, 76.19, 82.05, 86.44],
}

# Create DataFrame for additional hotels
additional_hotels_df = pd.DataFrame(additional_hotels_data, index=aspects).transpose()

# Combine all DataFrames
combined_df = pd.concat([existing_hotels_df, new_hotels_df, additional_hotels_df])

# Add a column for hotel names
combined_df["Hotel_Name"] = combined_df.index

# Reorder columns to place Hotel_Name first
columns = ["Hotel_Name"] + [col for col in combined_df.columns if col != "Hotel_Name"]
combined_df = combined_df[columns]

combined_df=combined_df.reset_index(drop=True)

combined_df.rename(columns={'Food': 'food','Service':'service','Clean':'clean','Room':'room','Staff':'staff','Location':'location'}, inplace=True)

In [13]:
combined_df

              Hotel_Name   food   clean  staff   room  location  service
0           Radisson Blu  92.68   96.49  90.68  80.41     86.04    93.44
1            Pride Plaza  84.38   73.91  90.48  66.07     82.61    94.53
2                Novotel  83.78   88.88  87.07  78.40     82.76    85.18
3             Lemon Tree  71.57   85.29  78.22  57.89     73.73    75.86
4            ITC Narmada  75.47   92.85  90.00  76.67     75.00    87.40
5                    Taj  73.33   78.13  83.49  77.91     80.60    87.61
6                Vivanta  80.00   87.10  81.90  75.00     82.69    87.10
7     Courtyard Marriott  61.67   77.42  75.65  71.08     80.26    75.47
8                 Ramada  92.11   85.71  87.50  60.71     86.36    80.65
9            Renaissance  70.45   80.00  64.60  61.39     76.06    64.54
10                  Cama  72.63   90.32  76.92  71.43     84.69    73.68
11                Cambay  22.22   23.91  28.87  20.15     35.85    23.86
12          Fortune Park  75.24   79.41  80.95  60.87     75.81    83.67
13          Four Seasons  75.00   76.32  84.13  53.21     80.28    79.25
14               Hillock  90.13  100.00  86.54  74.42     91.67    93.18
15           House of MG  68.53   90.00  75.76  72.34     83.18    62.34
16         Hyatt Regency  77.42   84.38  78.26  68.48     79.10    78.70
17             Metropole  68.63   68.00  65.85  52.13     84.06    65.48
18                Binori  68.42   73.08  62.16  65.22     87.10    57.32
19         Courtyard SBR  61.54   90.91  61.39  63.95     84.13    67.07
20           Crown Plaza  68.49   90.00  81.25  76.04     78.95    83.20
21  DoubleTree by Hilton  74.36   89.66  76.11  68.75     86.15    74.19
22    Fairfield Marriott  60.22   66.67  54.46  39.67     60.00    51.85
23        Fortune Select  75.35   66.67  74.11  60.44     82.05    76.24
24           Holiday Inn  79.76   92.31  84.95  44.34     86.67    84.92
25                 Hyatt  80.92   91.30  87.16  64.00     81.36    92.44
26             President  63.53   74.36  62.12  71.76     81.67    68.49
27       Regenta Central  69.70   64.10  61.84  55.56     72.22    71.76
28                 Ummed  64.84   75.00  66.67  53.85     79.10    60.23
29       WelcomHotel ITC  85.26   85.00  87.60  80.65     80.56    90.00
30               Wyndham  68.75   65.63  57.47  58.49     70.31    54.67
31      Fortune Landmark  87.50   80.49  84.55  76.19     82.05    86.44

In [26]:
import pandas as pd

# Data for the DataFrame
data = {
    "Hotel Name": [
        "Binori", "Fortune Landmark", "Wyndham", "WelcomHotel ITC", "The Ummed",
        "Regenta Central", "President", "Metropole", "Hyatt Regency", "House of MG",
        "Hillock", "Four Seasons", "Fortune Park", "Cambay", "Cama",
        "Renaissance", "Ramada", "Courtyard Marriott", "Vivanta", "Taj",
        "ITC Narmada", "Lemon Tree", "Novotel", "Pride Plaza", "Radisson Blu",
        "Hyatt", "Holiday Inn Prahaladnagar", "Fortune Select", "Fairfield Marriott",
        "DoubleTree by Hilton", "Crown Plaza", "Courtyard SBR"
    ],
    "Positive Aspects": [
        "room, location", "food, clean, staff, room, location, service", "",
        "food, clean, staff, room, location, service", "",
        "", "room, location", "location", "food, clean, staff, room, service",
        "clean, staff, room, location", "food, clean, staff, room, location, service",
        "food, staff, location, service", "food, staff, service",
        "", "clean, staff, room, location", "", "food, clean, staff, location, service",
        "staff, room, location, service", "food, clean, staff, room, location, service",
        "food, staff, room, location, service", "food, clean, staff, room, service",
        "clean, staff, service", "food, clean, staff, room, location, service",
        "food, staff, room, location, service", "food, clean, staff, room, location, service",
        "food, clean, staff, location, service", "food, clean, staff, location, service",
        "food, location, service", "", "food, clean, staff, room, location",
        "clean, staff, room, service", "clean, location"
    ],
    "Negative Aspects": [
        "food, clean, staff, service", "", "food, clean, staff, room, location, service",
        "", "food, clean, staff, room, location, service",
        "food, clean, staff, room, location, service", "food, clean, staff, service",
        "food, clean, staff, room, service", "location", "food, service",
        "", "clean, room", "clean, room, location",
        "food, clean, staff, room, location, service", "food, service",
        "food, clean, staff, room, location, service", "room", "food, clean",
        "", "clean", "location", "food, room, location", "", "clean",
        "", "room", "room", "clean, staff, room", "food, clean, staff, room, location, service",
        "service", "food, location", "food, staff, room, service"
    ],
}

# Create the DataFrame
hotel_aspects_df = pd.DataFrame(data)

In [27]:
hotel_aspects_df

,Hotel Name,Positive Aspects,Negative Aspects
0,Binori,"room, location","food, clean, staff, service"
1,Fortune Landmark,"food, clean, staff, room, location, service",
2,Wyndham,,"food, clean, staff, room, location, service"
3,WelcomHotel ITC,"food, clean, staff, room, location, service",
4,The Ummed,,"food, clean, staff, room, location, service"
5,Regenta Central,,"food, clean, staff, room, location, service"
6,President,"room, location","food, clean, staff, service"
7,Metropole,location,"food, clean, staff, room, service"
8,Hyatt Regency,"food, clean, staff, room, service",location
9,House of MG,"clean, staff, room, location","food, service"
10,Hillock,"food, clean, staff, room, location, service",
11,Four Seasons,"food, staff, location, service","clean, room"
12,Fortune Park,"food, staff, service","clean, room, location"
13,Cambay,,"food, clean, staff, room, location, service"
14,Cama,"clean, staff, room, location","food, service"
15,Renaissance,,"food, clean, staff, room, location, service"
16,Ramada,"food, clean, staff, location, service",room
17,Courtyard Marriott,"staff, room, location, service","food, clean"
18,Vivanta,"food, clean, staff, room, location, service",
19,Taj,"food, staff, room, location, service",clean
20,ITC Narmada,"food, clean, staff, room, service",location
21,Lemon Tree,"clean, staff, service","food, room, location"
22,Novotel,"food, clean, staff, room, location, service",
23,Pride Plaza,"food, staff, room, location, service",clean
24,Radisson Blu,"food, clean, staff, room, location, service",
25,Hyatt,"food, clean, staff, location, service",room
26,Holiday Inn Prahaladnagar,"food, clean, staff, location, service",room
27,Fortune Select,"food, location, service","clean, staff, room"
28,Fairfield Marriott,,"food, clean, staff, room, location, service"
29,DoubleTree by Hilton,"food, clean, staff, room, location",service
30,Crown Plaza,"clean, staff, room, service","food, location"
31,Courtyard SBR,"clean, location","food, staff, room, service"

In [45]:
def get_hotels_with_positive_aspect(df, aspect):
    """
    Fetches a list of hotel names where the given aspect is present in the "Positive Aspects" column.

    Parameters:
    df (pd.DataFrame): DataFrame containing hotel data with "Positive Aspects" column.
    aspect (str): The aspect to search for.

    Returns:
    list: A list of hotel names where the aspect is present in the "Positive Aspects" column.
    """
    return df[df["Positive Aspects"].str.contains(aspect, na=False)]["Hotel Name"].tolist()

In [49]:
best_hotels_with_aspect=get_hotels_with_positive_aspect(hotel_aspects_df, 'room')
final_result=get_top_hotels_from_list(combined_df, best_hotels_with_aspect, 'room')
final_result

['WelcomHotel ITC',
 'Radisson Blu',
 'Novotel',
 'Taj',
 'ITC Narmada',
 'Fortune Landmark',
 'Crown Plaza',
 'Vivanta',
 'Hillock',
 'House of MG']